apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-environment
  namespace: openshift-gitops-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/clbartolome/ocp-dev-101.git
    targetRevision: master
    path: demo-environment/resources/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops-operator
  syncPolicy: {}