apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lol-app-db
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem