---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-repositories
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-data
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi